package com.amk.driver;

import java.sql.SQLException;
import java.util.Optional;
import java.util.Scanner;

import com.amk.entity.EmployeeDetails;
import com.amk.service.EmployeeService;

public class Driver {
	public static void main(String[] args) throws ClassNotFoundException, SQLException {

		System.out.println("                            ***** WELCOME TO EMAIL SERVICE *****");
		System.out.println(" ");
		EmployeeDetails employeeDetails = new EmployeeDetails();
		EmployeeService employeeService = new EmployeeService();
		Scanner scan = new Scanner(System.in);
		int action = 0;
		int departmentChoice = 0;
		int rowsAffected = 0;
		System.out.println("PRESS 1 TO GENERATE EMAIL AND PASSWORD\nPRESS 2 TO SET NEW PASSWORD\n"
				+ "PRESS 3 TO FETCH EMPLOYEE DETAILS\nPRESS 4 TO DELETE EMPLOYEE\nPRESS 0 TO EXIT");
		try {
			action = scan.nextInt();
		} catch (Exception e) {
			System.out.println("SOMETHING WENT WRONG PROBABLY INPUT MISMATCH...");

		}
		scan.nextLine();// consuming the endline character generated by nextInt()
		switch (action) {
		case 1:
			System.out.println("ENTER YOUR FIRST NAME:");
			String firstName = scan.nextLine();
			employeeDetails.setFirstName(firstName);
			System.out.println("ENTER YOUR LAST NAME:");
			String lastName = scan.nextLine();
			employeeDetails.setLastName(lastName);
			System.out.println("ENTER DEPARTMENT\n 1 for sales\n 2 for IT\n 3 for Accounts \n 4 for Hr");
			try {
				departmentChoice = scan.nextInt();
			} catch (Exception e) {
				System.out.println("SOMETHING WENT WRONG PROBABLY INPUT MISMATCH...");
				scan.close();
				return;
			}
			employeeService.setDepartment(departmentChoice, employeeDetails);
			scan.nextLine();// consuming end line character generated due to nextInt()
			System.out.println("ENTER ALTERNATE EMAIL ID: ");
			employeeDetails.setAlternateEmailId(scan.nextLine());
			employeeService.generateEmployeeId();
			employeeService.generateEmail();
			employeeService.generatePassword();
			EmployeeDetails employeeStored = employeeService.addEmployeeDetails();
			if (employeeStored != null) {
				System.out.println("YOUR EMAIL ID IS: " + employeeStored.getGeneratedEmailId());
				System.out.println("YOUR EMPLOYEE ID IS: " + employeeStored.getEmployeeId());
				System.out.println("YOUR PASSWORD IS: " + employeeStored.getGeneratedPassword());
			} else
				System.out.println("Something went wromg....");
			break;
		case 2:
			System.out.println("ENTER EMPLOYEE ID:");
			String employeeId = scan.nextLine();
			System.out.println("ENTER YOUR NEW PASSWORD:");
			String newPassword = scan.nextLine();
			System.out.println(employeeService.changePassword(employeeId, newPassword));
			break;

		case 3:
			System.out.println("ENTER EMPLOYEE ID:");
			String id = scan.nextLine();
			Optional<EmployeeDetails> optional = employeeService.getEmployee(id);
			if (optional != null) {
				System.out.println(optional.get());
			} else
				System.out.println("Could not find any employee with given id...");
		case 4:
			System.out.println("ENTER THE EMPLOYEE ID:");
			String empId = scan.nextLine();
			rowsAffected = employeeService.deleteEmployee(empId);
			if (rowsAffected > 0) {
				System.out.println("Employee deleted successfully....");
			} else {
				System.out.println("Employee not found......");
			}
			break;

		default:
			System.exit(0);

		}

		scan.close();
	}

}
